name: Docker Autobuild, Autopush and Autobot

on:
  push:
    branches: [ "main" ]
    paths:
      - "lab-3/**"
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: "/lab-3"

    steps:
    - name: repository checkout
      uses: actions/checkout@v4


    - name: login to docker
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: build-push-docker
      uses: docker/build-push-action@v5
      with:
        context: ./lab-3/Base/
        push: true
        tags: KolaYAndr/oblaka:latest
