name: Docker Autobuild, Autopush and Autobot*

on:
  workflow_dispatch: 

jobs:
  build_and_push: 
    runs-on: self-hosted

    defaults:
      run:
        working-directory: "/lab3*"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Import Secrets
        uses: hashicorp/vault-action@v2.4.0
        with:
          url: http://127.0.0.1:8200
          tlsSkipVerify: true
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            secret/data/docker DOCKER_USERNAME ;
            secret/data/docker DOCKER_READ_WRITE_TOKEN

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_READ_WRITE_TOKEN }}

      - name: Build and push to Docker hub
        uses: docker/build-push-action@v5
        with:
          context: ./lab3
          push: true
          tags: kolayandr/oblaka:latest
